[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shiny-hdvc" 
version = "0.1.0"
dependencies = [ 
    "jupyter==1.1.1",
    "jupyterlab==4.4.10",
    "ipykernel==7.1.0"
]

[tool.setuptools.packages.find]
where = ["src"] 
